server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    jwt:
      secret: q113e123qf23t2cjeig2c292524v80wm0fvimw23ccfsgwgdsg4rc23
      expiration: 10m
      issuer: forum-app

logging:
  level:
    org.springframework: info
    org.hibernate.sql: debug